---
title: "Midwest"
author: "Weng Shian Ho"
date: "3/4/2018"
output: html_notebook
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load Data
```{r, echo=TRUE}
stock_data<- read.csv("/Users/wengshian/Documents/GitHub/Midwest_repo/Data/ticker_data.csv")
```

```{r, echo=TRUE}
factor_data<- read.csv("/Users/wengshian/Documents/GitHub/Midwest_repo/Data/factor_data.csv")
```
#################

```{r, echo=FALSE}
library(DataCombine)
stock_data<- with(stock_data,
       data.frame(model.matrix(~industry-1,stock_data),
                  index,market_cap,pb,returns,ticker,timestep))
```

```{r, echo=FALSE}
#calculate percentage change
# note that d_"factor" refers to proportional change from time interval before
library(DataCombine)
new_factor_data <- change(factor_data, Var = "VIX",
         type = 'proportion',
         NewVar = "d_VIX",
         slideBy = -1)
new_factor_data <- change(new_factor_data, Var = "COPP",
         type = 'proportion',
         NewVar = "d_COPP",
         slideBy = -1)
new_factor_data <- change(new_factor_data, Var = "X3M_R",
         type = 'proportion',
         NewVar = "d_X3M_R",
         slideBy = -1)

new_factor_data <- change(new_factor_data, Var = "US_TRY",
         type = 'proportion',
         NewVar = "d_US_TRY",
         slideBy = -1)

new_factor_data <- change(new_factor_data, Var = "BIG_IX",
         type = 'proportion',
         NewVar = "d_BIG_IX",
         slideBy = -1)

new_factor_data <- change(new_factor_data, Var = "SMALL_IX",
         type = 'proportion',
         NewVar = "d_SMALL_IX",
         slideBy = -1)

new_factor_data <- change(new_factor_data, Var = "SENTI",
         type = 'proportion',
         NewVar = "d_SENTI",
         slideBy = -1)
new_factor_data <- change(new_factor_data, Var = "TEMP",
         type = 'proportion',
         NewVar = "d_TEMP",
         slideBy = -1)
#normalize rain data (some 0s)
new_factor_data$RAIN <- scale(new_factor_data$RAIN)
new_factor_data <- change(new_factor_data, Var = "RAIN",
         type = 'proportion',
         NewVar = "d_RAIN",
         slideBy = -1)
new_factor_data <- change(new_factor_data, Var = "OIL",
         type = 'proportion',
         NewVar = "d_OIL",
         slideBy = -1)
```

```{r, echo=FALSE}
#contains data where row indices are time steps and col indices are factors and returns
stock_data_returns <- data.frame(stock_data$timestep,stock_data$ticker, stock_data$returns)
colnames(stock_data_returns)<- c("timestep","ticker","returns")
stock_data_returns<-reshape(stock_data_returns, direction = "wide", idvar = "timestep", timevar = "ticker")
new_stock_data <- merge(new_factor_data,stock_data_returns, by="timestep",all=TRUE)
```

```{r, echo=FALSE}
#new data with change in data factors lagged
lagged_stock_data<- data.frame(new_stock_data)

#institute a one day lag
lagged_stock_data[1:(nrow(lagged_stock_data)-1),22:1021] <- new_stock_data[2:nrow(lagged_stock_data),22:1021]
lagged_stock_data[1:(nrow(lagged_stock_data)-1),12:21] <- new_stock_data[2:nrow(lagged_stock_data),12:21]

```

```{r, echo=FALSE}
#information matrix consisting of all factor data and one-day lagged returns
pca_data<- data.frame(lagged_stock_data[2000:2520,12:21],lagged_stock_data[2000:2520,22:1021])
pca_data<- na.omit(pca_data)
mu = colMeans(pca_data)[1:10]
prin_comps <- prcomp(pca_data[,1:10],scale=TRUE)

#see how much the first few princ comps account for variance
stand_dev <- prin_comps$sdev
pr_var<- stand_dev^2
prop_var <- pr_var/sum(pr_var)
plot(prop_var, xlab = "Principal Component",
             ylab = "Proportion of Variance Explained",
             type = "b")

#reconstruct factors using first n principal components
n = 8
new_predictors = prin_comps$x[,1:n] %*% t(prin_comps$rotation[,1:n])
new_predictors = scale(new_predictors, center = mu, scale = FALSE)

```

```{r}
#run regression here
start_col = 10
regression_r_squared = numeric(length = 1000)
for (stock_num in 1:1000){
  stock_col = start_col + stock_num
  stock_data = pca_data[,stock_col]
  reg_model = lm(stock_data~new_predictors)
  regression_r_squared[stock_num] = summary(reg_model)$adj.r.squared
}
```

```{r}
# Ridge
library(glmnet)
start_col=10
ridge_r_sqr = array(0, dim=c(1,1000))

for (i in 1:1000){
  stock_col = start_col + i
  stock_data = pca_data[,stock_col]
  ridge = cv.glmnet(new_predictors,stock_data,alpha = 0,nlambda=100,lambda.min.ratio=0.0001)
  opt_lambda = ridge$lambda.min
  y_predicted = predict(ridge$glmnet.fit, s = opt_lambda, newx = new_predictors)
  sst = sum((stock_data - mean(stock_data))^2)
  sse = sum((y_predicted - stock_data)^2)
  ridge_r_sqr[i] = 1 - sse / sst
}

```
